
# commit to be tagged for the new release
commit = "HEAD"

project_name = "pulumi-provider-talos"
github_repo = "siderolabs/pulumi-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
pre_release = true

[notes]

    [notes.resource]
        title = "Secrets and GenConfig resource changes"
        description = """\
The talosconfig output has now been moved to the Secrets Resource and there is no talosconfig output for the GenConfig resource
"""

