// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Generate machine secrets for a Talos cluster
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@pulumi/talos";
 *
 * const machineSecrets = new talos.TalosMachineSecrets("machineSecrets", {});
 * ```
 */
export class TalosMachineSecrets extends pulumi.CustomResource {
    /**
     * Get an existing TalosMachineSecrets resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TalosMachineSecretsState, opts?: pulumi.CustomResourceOptions): TalosMachineSecrets {
        return new TalosMachineSecrets(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'talos:index/talosMachineSecrets:TalosMachineSecrets';

    /**
     * Returns true if the given object is an instance of TalosMachineSecrets.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TalosMachineSecrets {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TalosMachineSecrets.__pulumiType;
    }

    /**
     * The generated talos cluster secrets
     */
    public /*out*/ readonly machineSecrets!: pulumi.Output<string>;
    /**
     * The version of Talos for which to generate secrets
     */
    public readonly talosVersion!: pulumi.Output<string | undefined>;

    /**
     * Create a TalosMachineSecrets resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TalosMachineSecretsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TalosMachineSecretsArgs | TalosMachineSecretsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TalosMachineSecretsState | undefined;
            resourceInputs["machineSecrets"] = state ? state.machineSecrets : undefined;
            resourceInputs["talosVersion"] = state ? state.talosVersion : undefined;
        } else {
            const args = argsOrState as TalosMachineSecretsArgs | undefined;
            resourceInputs["talosVersion"] = args ? args.talosVersion : undefined;
            resourceInputs["machineSecrets"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["machineSecrets"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(TalosMachineSecrets.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TalosMachineSecrets resources.
 */
export interface TalosMachineSecretsState {
    /**
     * The generated talos cluster secrets
     */
    machineSecrets?: pulumi.Input<string>;
    /**
     * The version of Talos for which to generate secrets
     */
    talosVersion?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TalosMachineSecrets resource.
 */
export interface TalosMachineSecretsArgs {
    /**
     * The version of Talos for which to generate secrets
     */
    talosVersion?: pulumi.Input<string>;
}
