// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieve Kubeconfig for a Talos cluster
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@pulumi/talos";
 *
 * const machineSecrets = new talos.TalosMachineSecrets("machineSecrets", {});
 * const talosconfig = new talos.TalosClientConfiguration("talosconfig", {
 *     clusterName: "example-cluster",
 *     machineSecrets: machineSecrets.machineSecrets,
 *     endpoints: ["10.5.0.2"],
 * });
 * const kubeconfig = new talos.TalosClusterKubeconfig("kubeconfig", {
 *     talosConfig: talosconfig.talosConfig,
 *     endpoint: "10.5.0.2",
 *     node: "10.5.0.2",
 * });
 * ```
 */
export class TalosClusterKubeconfig extends pulumi.CustomResource {
    /**
     * Get an existing TalosClusterKubeconfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TalosClusterKubeconfigState, opts?: pulumi.CustomResourceOptions): TalosClusterKubeconfig {
        return new TalosClusterKubeconfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'talos:index/talosClusterKubeconfig:TalosClusterKubeconfig';

    /**
     * Returns true if the given object is an instance of TalosClusterKubeconfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TalosClusterKubeconfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TalosClusterKubeconfig.__pulumiType;
    }

    /**
     * machine endpoint
     */
    public readonly endpoint!: pulumi.Output<string>;
    /**
     * The retrieved Kubeconfig
     */
    public /*out*/ readonly kubeConfig!: pulumi.Output<string>;
    /**
     * node to use
     */
    public readonly node!: pulumi.Output<string>;
    /**
     * talos client configuration for authentication
     */
    public readonly talosConfig!: pulumi.Output<string>;

    /**
     * Create a TalosClusterKubeconfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TalosClusterKubeconfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TalosClusterKubeconfigArgs | TalosClusterKubeconfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TalosClusterKubeconfigState | undefined;
            resourceInputs["endpoint"] = state ? state.endpoint : undefined;
            resourceInputs["kubeConfig"] = state ? state.kubeConfig : undefined;
            resourceInputs["node"] = state ? state.node : undefined;
            resourceInputs["talosConfig"] = state ? state.talosConfig : undefined;
        } else {
            const args = argsOrState as TalosClusterKubeconfigArgs | undefined;
            if ((!args || args.endpoint === undefined) && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if ((!args || args.node === undefined) && !opts.urn) {
                throw new Error("Missing required property 'node'");
            }
            if ((!args || args.talosConfig === undefined) && !opts.urn) {
                throw new Error("Missing required property 'talosConfig'");
            }
            resourceInputs["endpoint"] = args ? args.endpoint : undefined;
            resourceInputs["node"] = args ? args.node : undefined;
            resourceInputs["talosConfig"] = args ? args.talosConfig : undefined;
            resourceInputs["kubeConfig"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["kubeConfig"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(TalosClusterKubeconfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TalosClusterKubeconfig resources.
 */
export interface TalosClusterKubeconfigState {
    /**
     * machine endpoint
     */
    endpoint?: pulumi.Input<string>;
    /**
     * The retrieved Kubeconfig
     */
    kubeConfig?: pulumi.Input<string>;
    /**
     * node to use
     */
    node?: pulumi.Input<string>;
    /**
     * talos client configuration for authentication
     */
    talosConfig?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TalosClusterKubeconfig resource.
 */
export interface TalosClusterKubeconfigArgs {
    /**
     * machine endpoint
     */
    endpoint: pulumi.Input<string>;
    /**
     * node to use
     */
    node: pulumi.Input<string>;
    /**
     * talos client configuration for authentication
     */
    talosConfig: pulumi.Input<string>;
}
